### ISSUE TITLE
Create comprehensive documentation how to build & use the LPSLAM ROS2 node

### ISSUE THREAD

**Issue by Trilion99** [lp-research/lpslam_node#1]
So far we don't have any public documentation linked to this project, not even build instructions. Need to add. Potentially we have something internally at LP, will check.

**Comment by jed87** [comment]
i am unable to colcon build OpenVSLAM-ROS wrapper. Please let me know if i did the steps correctly.

Followed the steps on for my xavier nx but failed to buiild.  [https://lp-research.atlassian.net/wiki/spaces/LKB/pages/1750761481/LPSLAM+for+ROS2+Documentation#OpenCV-(latest-%3E-3.0.0)](url)  .

May i know where should i put the following folders?
1. OpenVSLAM ( branch: feature/lpr-mods)
2. LPSLAM interfaces

I understand that OpenVSLAM is a submodule of lpslam and lpslam is a submodule of lpslam_node. 
lpslam_node >lpslam >openvslam

I created a folder named "Dependencies" and successfully cloned and make install for the followings:
- Pangolin
- Eigen
- DBoW2
- g2o

i then did a "git clone --recurse-submodules https://github.com/lp-research/lpslam_node.git"
followed by the steps to make OpenVSLAM in the submodule : lpslam_node >lpslam >openvslam

Lastly "git clone and colcon built LPSLAM interfaces"

Hence my Dependencies folder have :
- Pangolin
- Eigen
- DBoW2
- g2o
- LPSLAM interfaces
- OpenVSLAM-ROS wrapper 

i failed at the last step, which is the colcon build for OpenVSLAM-ROS wrapper.

**Comment by Trilion99** [comment]
Hi! I'm using cmake 3.16.3. Please feel free to make a ticket and / or pull request if you find any problem. This project is very much work in progress, any input is welcome.

**Comment by jed87** [comment]
Thank you for replying. 
Noticed that you all are using the ZED2 camera, do i need to install the zed ros2 wrapper and the ZED SDK? I have a ZED camera that i can test with.

**Comment by Trilion99** [comment]
Yes, please use the ZED camera wrapper for ROS2: https://github.com/stereolabs/zed-ros2-wrapper

**Comment by Trilion99** [comment]
@jed87 I'll close this issue, as we have created the first version of the documentation for this project: https://lp-research.atlassian.net/l/c/tRpxXT60

Let's stay in touch on Discord:
https://discord.gg/ZxkK3QdfQQ

If you can't access Discord please create a new ticket here, if you have problems with the build.
