### ISSUE TITLE
Trivial typo in the CMakeLists.txt?

### ISSUE THREAD

**Issue by yuki-inaho** [lp-research/lpslam_node#15]
Hello LP-RESEARCH development team,

I just found this repository a few minutes ago, and I'm currently confirming your codes.

And I found (probably unintentional) typo lines (at current [HEAD commit](https://github.com/lp-research/lpslam_node/commit/0ed2c5d31e70feaeff641ceeaee1044558e38515)) shown as below.

I know this is just my quibble on insignificant detail, but I hope this will be of some help. 

In the lines shown below , "lpslam or LPSLAM" is used.
https://github.com/lp-research/lpslam_node/blob/0ed2c5d31e70feaeff641ceeaee1044558e38515/CMakeLists.txt#L2-L49

In the lines shown below , "LPSPAM" is used.
https://github.com/lp-research/lpslam_node/blob/0ed2c5d31e70feaeff641ceeaee1044558e38515/CMakeLists.txt#L63-L124

Thanks,

**Comment by ItsJas** [comment]
Hello @yuki-inaho, 

Thank you so much for your feedback! 
You're absolutely right. We noticed this typo and it's going to be fixed once we merge the latest PR. 

Please feel free to test our solution if you have time and share your thoughts with us! 

Thanks,
Yasmine
